### ISSUE TITLE
Criar um ambiente de homologação, entre vários devices

### ISSUE THREAD

**Issue by felquis** [felquis/instacloser#12]

**Comment by hugofcampos** [comment]
Como seria isso Felquis? Tem alguma ferramenta em mente?

**Comment by felquis** [comment]
Atualmente conseguimos homologar (acessar um localhost) no computador, porém o mesmo não pode ser acesso pelo browser do celular.

O motivo, é que se vc acessa o IP da sua maquina pelo celular, a API do Instagram não deixa autenticar por que não é a URL de callback correta.

Esse é o problema que deve ser solucionado.

**Comment by hugofcampos** [comment]
Criar um deploy direto no celular resolveria?
